/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "surface-dim": "#131313",
        "on-surface": "#e5e2e1",
        "primary-fixed": "#60ff99",
        "on-secondary-fixed": "#00210c",
        "on-background": "#e5e2e1",
        "secondary-container": "#027038",
        "background": "#131313",
        "surface-container-highest": "#353534",
        "inverse-surface": "#e5e2e1",
        "primary": "#f1ffef",
        "surface-container-high": "#2a2a2a",
        "on-tertiary-fixed-variant": "#584400",
        "error-container": "#93000a",
        "tertiary-fixed": "#ffe08d",
        "on-primary-fixed": "#00210c",
        "surface-container-lowest": "#0e0e0e",
        "on-surface-variant": "#b9cbb9",
        "tertiary": "#fffaf7",
        "inverse-primary": "#006d37",
        "surface-container": "#201f1f",
        "tertiary-fixed-dim": "#e5c364",
        "secondary-fixed-dim": "#7eda96",
        "surface-variant": "#353534",
        "secondary-fixed": "#9af7b0",
        "primary-container": "#00ff88",
        "surface": "#131313",
        "primary-fixed-dim": "#00e479",
        "on-primary": "#003919",
        "inverse-on-surface": "#313030",
        "on-secondary-fixed-variant": "#005228",
        "error": "#ffb4ab",
        "outline-variant": "#3b4b3d",
        "on-primary-fixed-variant": "#005228",
        "on-primary-container": "#007139",
        "outline": "#849585",
        "on-tertiary-fixed": "#241a00",
        "on-secondary-container": "#94f0ab",
        "on-secondary": "#003919",
        "on-tertiary-container": "#795f01",
        "surface-tint": "#00e479",
        "surface-container-low": "#1c1b1b",
        "secondary": "#7eda96",
        "surface-bright": "#3a3939",
        "on-tertiary": "#3d2f00",
        "tertiary-container": "#ffdb79",
        "on-error-container": "#ffdad6",
        "on-error": "#690005"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "fontFamily": {
        "headline": ["Space Grotesk", "sans-serif"],
        "body": ["Manrope", "sans-serif"],
        "label": ["Manrope", "sans-serif"],
        "mono": ["JetBrains Mono", "monospace"]
      }
    },
  },
  plugins: [],
}
