import React, { useState, useEffect } from 'react';
import axios from 'axios';
import { motion } from 'framer-motion';
import Toast from './Toast';

interface ReportData {
  summary: string;
  root_causes: string[];
  recommendations: string[];
  severity: string;
}

const GeminiReportCard: React.FC<{ sessionId: string, analysis: any }> = ({ sessionId, analysis }) => {
  const [report, setReport] = useState<ReportData | null>(null);
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState(false);
  const [showToast, setShowToast] = useState(false);

  useEffect(() => {
    const fetchReport = async () => {
      setLoading(true);
      setError(false);
      try {
        const response = await axios.post('http://localhost:8080/api/report/', {
          session_id: sessionId,
          analysis: analysis
        });
        setReport(response.data);
        localStorage.setItem('gemini_report', JSON.stringify(response.data));
        // Show toast on success
        setShowToast(true);
        setTimeout(() => setShowToast(false), 4000);
      } catch (err) {
        console.error('Failed to fetch Gemini report:', err);
        setError(true);
      } finally {
        setLoading(false);
      }
    };

    if (sessionId && analysis) {
      fetchReport();
    }
  }, [sessionId, analysis]);

  const severityColor = (sev: string) => {
    if (sev === 'FAIR') return 'text-[#00ff88] border-[#00ff88]/30 bg-[#00ff88]/10';
    if (sev === 'LOW') return 'text-cyan-400 border-cyan-400/30 bg-cyan-400/10';
    if (sev === 'MODERATE') return 'text-yellow-400 border-yellow-400/30 bg-yellow-400/10';
    if (sev === 'HIGH') return 'text-orange-400 border-orange-400/30 bg-orange-400/10';
    return 'text-error border-error/30 bg-error/10';
  };

  if (loading) {
    return (
      <div className="bg-surface-container-lowest p-8 rounded-xl border border-primary-container/20 min-h-[300px] flex flex-col gap-4 shadow-[0_20px_50px_-12px_rgba(0,255,136,0.08)] overflow-hidden relative">
        {/* Shimmer sweep */}
        <div className="absolute inset-0 bg-gradient-to-r from-transparent via-[#00ff88]/[0.03] to-transparent -translate-x-full animate-[shimmer_2s_linear_infinite]" style={{ animation: 'shimmer 2s linear infinite', backgroundSize: '200% 100%' }} />
        <div className="flex items-center gap-3 mb-3">
          <div className="h-5 w-5 bg-surface-container-highest rounded" />
          <div className="h-5 w-44 bg-surface-container-highest rounded" />
          <div className="ml-auto h-4 w-16 bg-surface-container-highest rounded-full" />
        </div>
        {[100, 85, 70, 55, 90, 65].map((w, i) => (
          <div key={i} className={`h-3 bg-surface-container-highest rounded animate-pulse`} style={{ width: `${w}%`, animationDelay: `${i * 0.08}s` }} />
        ))}
        <div className="mt-4 h-px bg-outline-variant/20" />
        <div className="flex justify-between">
          <div className="h-3 w-24 bg-surface-container-highest rounded animate-pulse" />
          <div className="h-3 w-20 bg-surface-container-highest rounded animate-pulse" />
        </div>
        <p className="text-center text-[10px] font-mono text-zinc-700 uppercase tracking-widest mt-2 animate-pulse">Generating forensic analysis…</p>
      </div>
    );
  }

  if (error || !report) {
    return (
      <div className="bg-surface-container-lowest p-8 rounded-xl border border-primary-container/20">
        <h3 className="font-headline text-lg font-semibold text-primary-container mb-4">Analysis Insight</h3>
        <p className="text-on-surface-variant text-sm leading-relaxed">
          FairLens evaluated disparities across the selected attributes. System detected bias levels that require attention. Proceed to mitigation to rectify disparities.
        </p>
      </div>
    );
  }

  return (
    <>
      <Toast visible={showToast} message="AI Report generated by Gemini 1.5 Flash" icon="auto_awesome" variant="success" />

      <motion.div
        initial={{ opacity: 0, y: 16 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5, ease: [0.23, 1, 0.32, 1] }}
        className="bg-surface-container-lowest p-8 rounded-xl border border-primary-container/20 shadow-[0_20px_50px_-12px_rgba(0,255,136,0.08)] relative overflow-hidden flex flex-col"
      >
        <div className="absolute top-0 right-0 w-40 h-40 bg-primary-container/8 blur-3xl rounded-full pointer-events-none" />

        {/* Header */}
        <div className="flex items-center gap-3 mb-6 relative z-10">
          <div className="w-7 h-7 rounded-lg bg-[#00ff88]/10 border border-[#00ff88]/20 flex items-center justify-center shrink-0">
            <span className="material-symbols-outlined text-primary-container text-sm" style={{ fontVariationSettings: "'FILL' 1" }}>smart_toy</span>
          </div>
          <div>
            <h3 className="font-headline text-base font-semibold text-primary-container tracking-tight leading-none">Gemini Forensic Audit</h3>
            <p className="text-zinc-700 text-[9px] font-mono uppercase tracking-widest mt-0.5">AI-powered analysis</p>
          </div>
          <div className={`ml-auto text-[9px] font-mono font-bold uppercase tracking-widest px-3 py-1 rounded-full border ${severityColor(report.severity)}`}>
            {report.severity}
          </div>
        </div>

        <div className="space-y-6 font-body text-sm text-on-surface-variant leading-relaxed relative z-10 overflow-y-auto max-h-[500px] pr-2 custom-scrollbar">
          <div>
            <h4 className="text-on-surface font-bold mb-2 uppercase text-[10px] tracking-widest opacity-40">Executive Summary</h4>
            <p>{report.summary}</p>
          </div>

          <div>
            <h4 className="text-on-surface font-bold mb-2 uppercase text-[10px] tracking-widest opacity-40">Root Causes</h4>
            <ul className="space-y-2">
              {report.root_causes.map((rc, i) => (
                <li key={i} className="flex items-start gap-2">
                  <span className="text-[#00ff88]/50 text-xs mt-0.5 shrink-0">→</span>
                  {rc}
                </li>
              ))}
            </ul>
          </div>

          <div>
            <h4 className="text-on-surface font-bold mb-2 uppercase text-[10px] tracking-widest opacity-40">Recommendations</h4>
            <ol className="space-y-2">
              {report.recommendations.map((rec, i) => (
                <li key={i} className="flex items-start gap-3">
                  <span className="text-[9px] font-mono text-[#00ff88]/60 bg-[#00ff88]/8 border border-[#00ff88]/15 w-5 h-5 rounded flex items-center justify-center shrink-0 mt-0.5">{i + 1}</span>
                  <span className="text-on-surface">{rec}</span>
                </li>
              ))}
            </ol>
          </div>
        </div>

        <div className="mt-6 pt-4 border-t border-outline-variant/15 relative z-10 flex items-center justify-between">
          <div className="flex items-center gap-2 text-[9px] font-mono text-zinc-700 uppercase tracking-widest">
            <span className="material-symbols-outlined text-[10px]">lock</span>
            Processed locally
          </div>
          <div className="flex items-center gap-1.5 text-[9px] font-mono text-zinc-600">
            Generated by
            <span className="text-[#00ff88]/60 font-bold">Gemini 1.5 Flash</span>
          </div>
        </div>
      </motion.div>
    </>
  );
};

export default GeminiReportCard;

